# Trabajo Práctico Integrador


## Urban Flow

## Integrantes del grupo:

* DARDO DARIO CALLADO
* RICARDO MARTIN GONZALEZ
* SAUL EDGARDO VELIZ
* ROSENDO MANUEL ALVES

## Sprint 1

## Consideraciones Generales e Importantes

- Desarrollo base: Los puntos solicitados son la base del trabajo práctico. Es posible la ampliación sin restricciones del mismo.

- Organización del Notebook:
  - Agregar antes del ejercicio 01 una celda donde se importan todas librerías necesarias.

  - Utilizar un título para cada celda y escribir cada funcionalidad en una celda con título. Tener en cuenta agrupar las funcionalidades afines.

## Versionado y Trabajo en Equipo

- La entrega puede entregarse en grupos de máximo 6 personas (mínimo 1 / máximo 6) y la defensa es individual. Los grupos deben mantenerse a lo largo del trabajo integrador.

- Se debe considerar que es un trabajo en equipo y que cualquiera de los integrantes puede realizar modificaciones para cada día de trabajo.

- Control de Versiones: Utilizar herramientas de versionado. Vincularlo por token a tu cuenta personal de versionado en la nube.

- Colaboradores: Brindar acceso al repositorio a las siguientes cuentas:

  - lcd-sa182@ugr.edu.ar

  - fpasinato@ugr.edu.ar

- Changelog: Cada ejercicio/punto del trabajo práctico es considerado como un día distinto de trabajo. Debe quedar constancia en un archivo CHANGELOG.md de los cambios generados cada día.

- Agregar una variable llamada desactivar_git_push que solamente me permita desactivar los "git push".  

- El archivo README.md debe contener el sprint en el que nos encontramos y debe contener:
  - El objetivo.
  - La introducción y el contexto del sprint de trabajo.


## Criterios de evaluación

- Funcionalidad:

  - El código debe ejecutar sin errores al ejecutar "Ejecutar todo" (Ctrl+F9).

  - Se debe implementar la totalidad de las funcionalidades solicitadas.
  
  - La lógica del programa debe ser correcta y consistente.
  
  - Utilización de librerías acorde a los problemas a resolver.

  - Recordar antes de entregar de validar el notebook con los siguientes pasos. Ir al menú Runtine/Ejecutar -> Restart session and run all/Reiniciar la sessión y ejecutar todo

- Claridad y organización:

  - El código debe estar bien organizado y dividido.

  - Utilizar diferentes celdas de código para resolver cada solicitud/punto dentro de un ejercicio específico con su comentario "title" correspondiente a la solución implementada.
  
  - Se deben utilizar nombres de variables que describan su contenido/función.
  
  - Se debe agregar comentarios explicativos y necesarios según estandares.

  - Todos los imports deben ubicarse en la primer celda de ejecución arriba de la descripción del "Ejercicio 01".

  - No se admite la sentencia "git add ." para simplificar el traceo.
  
  - No se admiten comentarios innecesarios dentro del código. Solo comentar funciones, clases, métodos y propiedades de clase.

- Estilo y presentación:

  - Se debe usar una indentación consistente y un formato de código adecuado.

  - Se deben evitar comentarios redundantes o irrelevantes.

  - Se debe presentar el código de forma ordenada y profesional.
  
  - Se debe utilizar [type hints](https://docs.python.org/3/library/typing.html).
  
  - Se deben utilizar comentarios según el [pep8](https://peps.python.org/pep-0008/).

- Herramientas:
  
  - Utilizar principalmente librerías vistas durante la cursada. No se admiten librerías similares a las vistas en la materia.

  - Utilizar librerías extras con criterios fundamentados, es decir, no utilizar por utilizar.

  - Indentar a 2 espacios y cortar a 80 caracteres según estandares.

  - No se puede utilizar gdrive.
  
  - No se pueden utilizar herramientas alternativas a las vistas durante la cursada.

## Condiciones de Entrega
- Formato de Archivo: Los estudiantes deberán enviar un archivo con extensión .ipynb.

- Nomenclatura: El nombre original del archivo debe reemplazar los valores indicados. Ejemplo: 0X_Price_Manager-Apellidos_Nombres.ipynb.

- Estado de la entrega:
  - Deberá entregarse ejecutado y con los datos precargados.
  - Deberá entregarse el desarrollo sobre una copia de la plantilla original.

- Canal de Entrega: La entrega se realiza en el aula virtual y solo se aceptan archivos (cualquier otra forma se considerará inválida). Solo se recibirán trabajos por correo adjunto a lcd-sa182@ugr.edu.ar si el plazo en la plataforma ha finalizado. No se aceptarán enlaces sueltos.

## Recomendaciones y Consecuencias del Incumplimiento
- Recomendaciones: Comenzar a trabajar con suficiente antelación. Leer y comprender el enunciado en su totalidad. Realizar consultas ante dudas al correo: lcd-sa182@ugr.edu.ar o fpasinato@ugr.edu.ar. La entrega en tiempo y forma es fundamental.

- Incumplimiento: Los trabajos que no cumplan con los requisitos no serán tomados en cuenta como nota final. Solo serán corregidos y evaluados con nota para la devolución correspondiente. Se considera incumplimiento a:

  - Entregas fuera de término.

  - Trabajos que no se entreguen sobre la plantilla de trabajo estipulada.

  - Trabajos que no se ejecuten completos (que contengan errores intermedios al dar "Ejecutar todo").

---

## Objetivo

El objetivo principal de este proyecto es aplicar los conocimientos adquiridos en para el versionado de código, la organización, limpieza del código y la utilización de pandas.

## Introducción y Contexto del problema

### Sprint 1

La localidad llamada Vaalserberg de Bélgica se encuentra en la zona fronteriza y limita con los paises de Países Bajos y Alemania. Esta localidad cuenta con un sistema de radares urbanos para la detección de infracciones por exceso de velocidad. Los registros históricos provienen de sistemas heredados, el cuál presenta errores de formato, faltante de datos generando registros inconsistentes en el nuevo sistema.

Debemos analizar y depurar los datos de viejo sistema para obtener información relevante sobre las infracciones y de está forma en el futuro poder incorporar los datos al nuevo sistema sin inconsistencias.

Descargar el dataset [speeding fines](https://raw.githubusercontent.com/HAD141/datasets/refs/heads/main/TrabajosPracticos/urban_flow/speeding_fines.csv) https://raw.githubusercontent.com/HAD141/datasets/refs/heads/main/TrabajosPracticos/urban_flow/speeding_fines.csv

El dataset contiene información histórica de multas por exceso de velocidad y presenta errores que deberán ser tratados para evitar inconsistencias.

---

In [2]:
import pandas as pd
import os

## Ejercicio 01

> Puntos: 1

Inicialización y configuración de la herramienta de versionado. Vamos a trabajar sobre la rama llamada "Sprint_1".

La estructura de directorios es:

```
├── urban_flow
│   ├── data
│   │   ├── interim (almacena dataset procesados de pasos intermedios)
│   │   │   ├── plots
│   │   ├── processed (almacena dataset procesados finales para entregar a otra aplicación)
│   │   ├── raw (almacena los dataset en crudo, sin procesar)
```

In [2]:
# Variable de control de versionado
desactivar_git_push = True  # permite desactivar los "git push"

## Ejercicio 02

> Puntos: 1

Los desarrollos que deben realizar son:

- Descargar el dataset raw original y almacenarlo en `urban_flow/data/raw`.

- Mostrar las 5 primeras filas.

- Analizar tipos de datos

- Contar los valores nulos.

In [30]:
# Crear la estructura de carpeta si no existe
os.makedirs("urban_flow/data/raw", exist_ok=True)

# URL dataset
url = "https://raw.githubusercontent.com/HAD141/datasets/refs/heads/main/TrabajosPracticos/urban_flow/speeding_fines.csv"

# Descarga y guardado del dataset
df = pd.read_csv(url)
df.to_csv("urban_flow/data/raw/speeding_fines.csv", index=False)

# Mostrar primeras 5 filas
print("Primeeras 5 filas:")
display(df.head())

# Tipos de datos
print("\n Tipos de datos:")
print(df.dtypes)

# Valores Nulos
print("\n Valores nulos por columna:")
print(df.isnull().sum())

Primeeras 5 filas:

,multa_id,patente,fecha,hora,velocidad_registrada,velocidad_maxima,ubicacion,radar_id,estado_multa
0,1,FD 1475,24/09/2021,09:01 AM,NaN,60,Av. Siempre Viva,R01,APELADA
1,2,0695 DVH,19/05/2020,18:01,NaN,40,Av Siempre Viva,NaN,APELADA
2,3,WU 341 A,2022/07/17,09:01 AM,107.0,60,AV LIBERTADOR,R03,PAGADA
3,4,GN64 OTP,invalid_date,invalid_hour,NaN,60,Ruta 9,NaN,APELADA
4,5,BX 55 DOG,2021/01/21,invalid_hour,94.0,60,Av. Siempre Viva,NaN,ERROR

 Tipos de datos:
multa_id                  int64
patente                  object
fecha                    object
hora                     object
velocidad_registrada    float64
velocidad_maxima          int64
ubicacion                object
radar_id                 object
estado_multa             object
dtype: object

 Valores nulos por columna:
multa_id                   0
patente                   50
fecha                      0
hora                       0
velocidad_registrada    1957
velocidad_maxima           0
ubicacion                  0
radar_id                1002
estado_multa               0
dtype: int64

## Ejercicio 03

> Puntos: 2

Utilizando Pandas:

- Normalizar las de fechas con el formato 'YYYY-MM-DD', en caso de fechas inválidas completar con la fecha `1932-01-01`. Mostrar las 10 primeras fechas.

- Normalizar los horas al formato de 24hs, las horas inválidas se procesaran como `00:00`. Mostrar las 10 primeras horas.

- Normalizar las ubicaciones. Quitar caracteres especiales y pasar todo a mayúsculas. Mostrar las 10 primeras ubicaciones.

- Limpiar y normalizar las patentes, en caso de error completar con pd.NA (no disponible/not available). Quitar caracteres especiales y pasar todo a mayúsculas. Mostrar las 10 últimas patentes.

- Eliminar las filas que posean valores relevantes para las multas y que se encuentren vacios. Mostrar la cantidad de registros eliminados y cuales son las columnas que se observaron utilizando la leyenda
```
Se eliminaron X filas.
Las columnas observadas son:
 - XXX
 - XXX
 - ...
```

- Detectar y eliminar los outliers. Mostrar la cantidad de registros eliminados y cuales son las columnas que se observaron utilizando la leyenda
```
Se eliminaron X filas.
Las columnas observadas son:
 - XXX
 - XXX
 - ...
```

- Crear la columna `exceso_velocidad_real` y calcularla. El exceso de velocidad real es la diferencia entre velocidad_registrada y la velocidad_maxima. Mostrar las primeras 10 patentes y su exceso de velocidad real.

- Crear la columna `exceso_velocidad` y calcularla. El exceso de velocidad es la diferencia entre velocidad_registrada y la velocidad_maxima más un 5 porciento de la velocidad máxima. Mostrar las primeras 10 patentes y su exceso de velocidad.

- Eliminar las filas que no cometieron infracciones según el exceso de velocidad.Mostrar cuantas filas se eliminaron con la leyenda
```
Se eliminaron X filas.
```

- Guardar el dataset limpio en `urban_flow/data/interim/speeding_fines.csv`

### Normalizar fechas:

In [31]:
# Normalizar las de fechas con el formato 'YYYY-MM-DD':
df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce', format='mixed')
df['fecha'].dt.strftime('%Y-%m-%d')
# Completar las fechas inválidas con "1932-01-01":
df['fecha'] = df['fecha'].fillna(pd.to_datetime('1932-01-01'))

print("Primeras 10 fechas normalizadas:")
df['fecha'].head(10)

Primeras 10 fechas normalizadas:

0   2021-09-24
1   2020-05-19
2   2022-07-17
3   1932-01-01
4   2021-01-21
5   2023-07-27
6   2023-06-16
7   2023-01-11
8   1932-01-01
9   1932-01-01
Name: fecha, dtype: datetime64[ns]

### Normalizar horas:

In [32]:
# Normalizar los horas al formato de 24hs:
df['hora'] = pd.to_datetime(df['hora'], errors='coerce').dt.strftime('%H:%M')
# Las horas inválidas se procesaran como 00:00.
df['hora'] = df['hora'].fillna('00:00')

print("Primeras 10 horas normalizadas:")
df['hora'].head(10)

Primeras 10 horas normalizadas:

/tmp/ipykernel_60183/2763004796.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['hora'] = pd.to_datetime(df['hora'], errors='coerce').dt.strftime('%H:%M')

0    09:01
1    18:01
2    09:01
3    00:00
4    00:00
5    00:00
6    18:01
7    08:01
8    09:01
9    14:01
Name: hora, dtype: object

### Normalizar ubicaciones

In [33]:
# Mediante la expresión regular [^a-zA-Z0-9\s] conservo sólo caracteres
# alfanuméricos y espacios (\s).
df['ubicacion'] = df['ubicacion'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
df['ubicacion'].str.upper()

print("Primeras 10 ubicaciones normalizadas:")
df['ubicacion'].head(10)

Primeras 10 ubicaciones normalizadas:

0    Av Siempre Viva
1    Av Siempre Viva
2      AV LIBERTADOR
3             Ruta 9
4    Av Siempre Viva
5    Av Siempre Viva
6      Av Libertador
7    Av Siempre Viva
8    Av Siempre Viva
9      Av Libertador
Name: ubicacion, dtype: object

### Limpiar y normalizar patentes:

In [34]:
 #Quitar caracteres especiales:
df['patente'] = df['patente'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
# Completo los vacíos con pd.NA
df['patente'] = df['patente'].replace('', pd.NA)
# Completo los erróneos con pd.NA
df['patente'] = df['patente'].fillna(pd.NA)

df['patente'].str.upper()

print("Últimas 10 patentes normalizadas:")
df['patente'].tail(10)

Últimas 10 patentes normalizadas:

3990    N HZ 1002
3991     MX60 NZA
3992      831 MDB
3993      M20 CPR
3994       BM 351
3995    M PX 9357
3996      831 MDB
3997      BB 8986
3998      8B90638
3999    691 XC 80
Name: patente, dtype: object

### Limpieza de valores relevantes para multas:

In [35]:
# Eliminar las observaciones con valores nulos en los atributos
# "velocidad_registrada", "velocidad_maxima", "radar_id":
atributos_relevantes = ["velocidad_registrada", "velocidad_maxima", "radar_id"]
total_observaciones = df.shape[0]

for atributo in atributos_relevantes:
    df = df.dropna(subset=[atributo])

total_observaciones = total_observaciones - df.shape[0]

print(f"Se eliminaron {total_observaciones} filas.")

print("Las columnas observadas son:")
for atr in atributos_relevantes:
    print(f" - {atr}")

Se eliminaron 2447 filas.
Las columnas observadas son:
 - velocidad_registrada
 - velocidad_maxima
 - radar_id

### Detección y limpieza de outliers:

In [36]:
# Detectar y eliminar los outliers. Mostrar la cantidad de registros
# eliminados y cuales son las columnas que se observaron

atributos_relevantes = ["velocidad_registrada", "velocidad_maxima"]
total_observaciones = len(df)

#Método del rango intercuartílico (IQR):
serie_vr = pd.to_numeric(df["velocidad_registrada"], errors='coerce')
Q1_vr = serie_vr.quantile(0.25)
Q3_vr = serie_vr.quantile(0.75)
IQR_vr = Q3_vr - Q1_vr
limite_inferior_vr = Q1_vr - 1.5 * IQR_vr
limite_superior_vr = Q3_vr + 1.5 * IQR_vr

#Eliminar outliers según atributo "velocidad_registrada":
df.drop(df[(df["velocidad_registrada"] < limite_inferior_vr) |
      (df["velocidad_registrada"] > limite_superior_vr)].index, inplace=True)

serie_vm = pd.to_numeric(df["velocidad_maxima"], errors='coerce')
Q1_vm = serie_vm.quantile(0.25)
Q3_vm = serie_vm.quantile(0.75)
IQR_vm = Q3_vm - Q1_vm
limite_inferior_vm = Q1_vm - 1.5 * IQR_vm
limite_superior_vm = Q3_vm + 1.5 * IQR_vm

# Eliminar outliers según "velocidad_maxima":
df.drop(df[(df["velocidad_maxima"] < limite_inferior_vm) |
 (df["velocidad_maxima"] > limite_superior_vm)].index, inplace=True)

total_observaciones = total_observaciones - len(df)

print(f"Se eliminaron {total_observaciones} filas.")
print("Las columnas observadas son:")
for atributo in atributos_relevantes:
    print(f" - {atributo}")

if not total_observaciones:
    print("No se encontraron outliers.")

Se eliminaron 0 filas.
Las columnas observadas son:
 - velocidad_registrada
 - velocidad_maxima
No se encontraron outliers.

### Nuevo atributo `exceso_velocidad_real`:

In [37]:
df["exceso_velocidad_real"] = df["velocidad_registrada"] - df["velocidad_maxima"]

print("Primeras 10 patentes y su exceso de velocidad:")
print(df[["patente", "exceso_velocidad_real"]].head(10).to_string(index=False))
print()

Primeras 10 patentes y su exceso de velocidad:
  patente  exceso_velocidad_real
 WU 341 A                   47.0
    BP717                   10.0
  OUTSTDN                   31.0
 TL03 GOG                   -2.0
57 777 70                   53.0
 BHRP 770                   11.0
  RFH 373                   41.0
  X IIUME                   12.0
    BP717                   -6.0
  M20 CPR                    2.0

### Nuevo atributo `exceso_velocidad`:

In [38]:
df["exceso_velocidad"] = df["velocidad_registrada"] - (df["velocidad_maxima"] * 1.05)
print(df[["patente", "exceso_velocidad"]].head(10).to_string(index=False))

  patente  exceso_velocidad
 WU 341 A              44.0
    BP717               7.0
  OUTSTDN              29.0
 TL03 GOG              -4.0
57 777 70              51.0
 BHRP 770               8.0
  RFH 373              37.0
  X IIUME              10.0
    BP717             -10.0
  M20 CPR              -1.0

### Limpieza de no infractores:

In [39]:
total_observaciones = len(df)
df.drop(df[df["exceso_velocidad"] <= 0].index, inplace=True)
total_observaciones = total_observaciones - len(df)

print(f"Se eliminaron {total_observaciones} filas.")

Se eliminaron 237 filas.

## Ejercicio 04

> Puntos: 2

Definir una clase FineAnalyzer que cumpla con las siguientes funcionalidades:

- Reciba el DataFrame limpio como argumento de inicialización.

- Encapsule correctamente los datos.

- Implemente métodos para:

  - Ranking de las patentes más multadas (top 5). Debe retornar un DataFrame ordenado de mayor a menor y el índice debe comenzar desde 1, con las columnas de patentes y cantidad..

  - Ranking de los horarios donde se producen más multas (top 5). Debe retornar un DataFrame ordenado de mayor a menor y el índice debe comenzar desde 1, con las columnas de hora y cantidad.


  - Exceso promedio de velocidad. Debe retorna un flotante.

  - Exceso real promedio de velocidad . Debe retorna un flotante.

  - Contabilizar la cantidad de multas por cada  ubicación. Debe retornar un DataFrame ordenado por ubicación mostrando la ubicación y la cantidad.

- Crear el objecto e invocar cada uno de los métodos en celdas separadas.

## Punto 05

> Puntos: 2


Responder a cada punto con un gráfico.

- Ranking de las 10 patentes más reincidentes ordenadas de mayor a menor. Exportar el gráfico con el nombre `ubran_flow/data/interim/plots/fines.jpg`


- Mostrar el porcentaje de infracciones por hora en un gráfico de torta. Exportar el gráfico con el nombre `ubran_flow/data/interim/plots/hours.jpg`

- Mostrar la cantidad de infracciones por mes en un gráfico de barras horizontal ordenado de mayor a menor. Exportar el gráfico con el nombre `ubran_flow/data/interim/plots/months.jpg`

- Mostrar en un gráfico de líneas de los excesos de velocidad agrupados por la hora 00:00. Exportar el gráfico con el nombre `ubran_flow/data/interim/plots/hour.jpg`

- Mostrar en un gráfico de líneas de los excesos de velocidad agrupados por la fecha 1932-01-01. Exportar el gráfico con el nombre `ubran_flow/data/interim/plots/date.jpg`

## Punto 06

> Puntos: 1

- Mostrar el porcentaje de infracción que se produjeron en la fecha 1932-01-01.

```
El porcentaje de infracciones en la fecha 1932-01-01 es XX.XX%
```

- Mostrar el porcentaje de infracción que se produjeron en la hora 00:00.
```
El porcentaje de infracciones a la hora 00:00 es XX.XX%
```

## Punto 07

> Puntos: 1



Redactar una conclusión acerca de los datos que contiene el dataset.

In [ ]:
%%writefile -a data/Readme.md

Writing data/Readme.md

FileNotFoundError: [Errno 2] No such file or directory: 'data/Readme.md'